Patient_Systems/Models/Patient_Data.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Patient_Systems.Models
{
    public partial class Patient_Data
    {
        public int ID { get; set; }
        
        [Required(ErrorMessage = "Please enter name"), MaxLength(40)]
        public string Full_Name { get; set; }

        [Required(ErrorMessage = "Please enter Address"), MaxLength(20)]
        public string Address { get; set; }

        public string Age { get; set; }

        public string Gender { get; set; }

        [RegularExpression("([0-9]+)", ErrorMessage = "Please enter valid Phone Number")]
        public string Mobile { get; set; }

        public string Image { get; set; }

        public virtual ICollection<Results> results { get; set; }
    }
}

Patient_Systems/Controllers/Patient_DataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Patient_Systems.Models;
using System.IO;
using Rotativa.MVC;

namespace Patient_Systems.Controllers
{
    [Authorize(Roles = "employee")]

    public class Patient_DataController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Patient_Data
        public ActionResult Index()
        {
            using (var context = new ApplicationDbContext())
            {
                var data = db.PatientData.SqlQuery("[dbo].[Get_ALL_Patient_Data]").ToList();
                return View(data);
            }

        }
        // GET: Patient_Data/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient_Data patient_Data = db.PatientData.Find(id);
            if (patient_Data == null)
            {
                return HttpNotFound();
            }
            return View(patient_Data);
        }
        public ActionResult PrintOne()
        {
            var p = new ActionAsPdf("Details");
            return p;
        }
        // GET: Patient_Data/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patient_Data/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Patient_Data patient_Data)
        {

            if (ModelState.IsValid)
            {
                string fileName = Path.GetFileNameWithoutExtension(patient_Data.ImageFile.FileName);
                string extension = Path.GetExtension(patient_Data.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                patient_Data.Image = "~/Content/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                patient_Data.ImageFile.SaveAs(fileName);
                db.PatientData.Add(patient_Data);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        // GET: Patient_Data/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient_Data patient_Data = db.PatientData.Find(id);
            if (patient_Data == null)
            {
                return HttpNotFound();
            }
            return View(patient_Data);
        }

        // POST: Patient_Data/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Full_Name,Address,Age,Gender,Mobile,Image")] Patient_Data patient_Data)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient_Data).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient_Data);
        }

        // GET: Patient_Data/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient_Data patient_Data = db.PatientData.Find(id);
            if (patient_Data == null)
            {
                return HttpNotFound();
            }
            return View(patient_Data);
        }

        // POST: Patient_Data/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient_Data patient_Data = db.PatientData.Find(id);
            db.PatientData.Remove(patient_Data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Patient_Systems/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Patient_Systems.Models;
using Rotativa;
using Rotativa.MVC;

namespace Patient_Systems.Controllers

{
    //[Authorize(Roles = "employee")]

    public class ResultsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Results
        public ActionResult Index()
        {
            using (var context = new ApplicationDbContext())
            {
                var data = db.results.SqlQuery("[dbo].[Get_ALL_Results]").ToList();
                return View(data);
            }

        }
        public ActionResult Print()
        {
            var p = new ActionAsPdf("Index");
            return p;
        }
    }



    }

Patient_Systems/Views/Patient_Data/Create.cshtml
@model Patient_Systems.Models.Patient_Data

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Patient_Data", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient_Data</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Full_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Full_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Full_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div style="font-size:20px;font-weight:bold;"> Add Image </div>
            <br />
            <div class="col-md-10">
                <input type="file" name="ImageFile" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Patient_Systems/Views/Patient_Data/Delete.cshtml
@model Patient_Systems.Models.Patient_Data

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient_Data</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Full_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Patient_Systems/Views/Patient_Data/Details.cshtml
@model Patient_Systems.Models.Patient_Data

@{
    ViewBag.Title = "Details";
}

<h2 style="text-align:center;">Details</h2>

<div class="row">
    <div class="col-lg-6">
        <div style="height:400px;width:100%;border-radius:20px;border:1px solid white;">
            <img src="@Url.Content(Model.Image)" style="height:400px;width:100%;border-radius:20px;border:1px solid white;" />
        </div>
    </div>
    <div class="col-lg-6">
        <br /><br /><br />
        <span>@Html.DisplayNameFor(model => model.Full_Name)</span> | @Html.DisplayFor(model => model.Full_Name)<br />
        <span>@Html.DisplayNameFor(model => model.Address)</span> | @Html.DisplayFor(model => model.Address)<br />
        <span>@Html.DisplayNameFor(model => model.Age)</span> | @Html.DisplayFor(model => model.Age)<br />
        <span>@Html.DisplayNameFor(model => model.Gender)</span> | @Html.DisplayFor(model => model.Gender)<br />
       <span>@Html.DisplayNameFor(model => model.Mobile)</span> | @Html.DisplayFor(model => model.Mobile)
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Patient_Systems/Views/Patient_Data/Edit.cshtml
@model Patient_Systems.Models.Patient_Data

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Patient_Data", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient_Data</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Full_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Full_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Full_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Patient_Systems/Views/Patient_Data/Index.cshtml
@model IEnumerable<Patient_Systems.Models.Patient_Data>

@{
    ViewBag.Title = "getall";
}

<h2 style="text-align:center">Patient Data</h2>
<button style="border-radius:10px;background-color:blueviolet;height:40px;width:200px;">@Html.ActionLink("Patient_Result", "Index", "Results",null,new { @style="Color:black;font-weight:bold;font-size:20px"})</button>
<br>
<br>
@Html.ActionLink("Create New", "Create")
    @foreach (var item in Model)
    {
        <div class="col-lg-3" style="height:250px;width:280px;">
            <img src="@Url.Content(item.Image)" style="height:200px;width:200px;border-radius:10px;" />
            <br />
            <span>Name &nbsp;&nbsp; @Html.DisplayFor(modelItem => item.Full_Name)</span>
            <br />
            <span>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </span>
        </div>


    }

    </div>